name: Publish Linux MDR Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  upload-to-azure-storage:
    name: Upload Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tweaks
        run: |
          sed 's/curl\ -s/curl\ -s4/' linux_onboarding.sh >install-ipv4.sh
          sed 's/curl\ -s/curl\ -s6/' linux_onboarding.sh >install-ipv6.sh
          sed 's/curl\ -s/curl\ -sk/' linux_onboarding.sh >install-insecure.sh

      - name: Upload Generic file to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload \
              --container-name mdr \
              --name install.sh \
              --file linux_onboarding.sh \
              --overwrite \
              --account-name delinianinfosec \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}

      - name: Upload IPv4 file to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload \
              --container-name mdr \
              --name install-ipv4.sh \
              --file install-ipv4.sh \
              --overwrite \
              --account-name delinianinfosec \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}

      - name: Upload IPv6 file to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload \
              --container-name mdr \
              --name install-ipv6.sh \
              --file install-ipv6.sh \
              --overwrite \
              --account-name delinianinfosec \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}

      - name: Upload insecure file to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload \
              --container-name mdr \
              --name install-insecure.sh \
              --file install-insecure.sh \
              --overwrite \
              --account-name delinianinfosec \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}